-- 7. Seed Data / Mock State (CPUT Bulletin Board)
-- Insert Users (Sellers and Organizers)
INSERT IGNORE INTO `users` (`id`, `email`, `password`, `full_name`, `role`, `institution_or_business`, `verified`, `verification_status`) VALUES 
(1, 'admin@cput.ac.za', 'password123', 'CPUT Admin', 'ADMIN', 'Cape Peninsula University of Technology', TRUE, 'APPROVED'),
(2, 'thabo.m@mycput.ac.za', 'password123', 'Thabo M.', 'USER', 'CPUT - Civil Engineering 2nd Year', TRUE, 'APPROVED'),
(3, 'ayesha.k@mycput.ac.za', 'password123', 'Ayesha K.', 'USER', 'CPUT - Hotel Management Alum', TRUE, 'APPROVED'),
(4, 'liam.d@mycput.ac.za', 'password123', 'Liam D.', 'USER', 'CPUT Student', TRUE, 'APPROVED'),
(5, 'naledi.p@mycput.ac.za', 'password123', 'Naledi P.', 'USER', 'CPUT Student', TRUE, 'APPROVED');

-- Insert Bulletin Posts (Events & Announcements)
INSERT IGNORE INTO `bulletin_posts` (`id`, `title`, `content`, `post_type`, `tags`, `author_id`, `event_date`) VALUES 
(1, 'CPUT Annual Work-Integrated Learning & Career Fair', 'Over 35 corporate, tech, engineering, and finance recruiters on campus. Ideal for 2nd, 3rd year, and Advanced Diploma students seeking in-service training, internships, and graduate programmes. Bring updated CVs and student card.\n\nType: Career & Networking\nCampus: Bellville Campus\nVenue: Major Sports Hall, Symphony Way\nTime: 09:00 - 15:30\nOrganizer: Centre for Community Engagement & Work-Integrated Learning (WIL)\nContact: careers@cput.ac.za', 'EVENT', 'careers, WIL, internships, networking, engineering, business', 1, '2026-08-14 09:00:00'),
(2, 'CPUT SRC Spring Market Day & Buskers Showcase', 'Student entrepreneurs selling food, vintage thrifts, custom prints, handmade jewellery, and beauty products. Features live lunchtime performances by the CPUT Performing Arts Society.\n\nType: Student Life & Enterprise\nCampus: District Six Campus\nVenue: Student Centre Piazza & Admin Quad, Hanover Street\nTime: 10:00 - 15:00\nOrganizer: Department of Student Affairs (DSA) & Central SRC\nContact: dsa@cput.ac.za', 'EVENT', 'market-day, student-business, food, music, campus-life', 1, '2026-09-18 10:00:00'),
(3, 'Faculty of Informatics and Design (FID) Graduate Showcase', 'End-of-year public exhibition showcasing final-year capstones in Architecture, Interior Design, Graphic Communication, Multimedia, and IT software prototypes. Industry judges and scouts attending.\n\nType: Exhibition & Academic\nCampus: District Six Campus\nVenue: Design Building (FID Atrium)\nTime: 11:00 - 18:00\nOrganizer: Faculty of Informatics and Design\nContact: fid-events@cput.ac.za', 'EVENT', 'design, informatics, showcase, architecture, coding', 1, '2026-11-20 11:00:00'),
(4, 'Varsity Shield Clash: CPUT Tekkies vs. UFH Blues', 'Support the boys in blue and gold for the home leg fixture. Free entry with valid CPUT student card. Food trucks and DJ booth opening at 17:30.\n\nType: Sports\nCampus: Bellville Campus\nVenue: CPUT Bellville Stadium\nTime: 19:00 kickoff\nOrganizer: CPUT Sport, Arts & Culture\nContact: sports@cput.ac.za', 'EVENT', 'rugby, varsity-shield, sports, tekkies', 1, '2026-03-23 19:00:00'),
(5, 'CPUT Institutional Open Day 2026', 'Showcasing course offerings across all 6 faculties: Applied Sciences, Business & Management Sciences, Education, Engineering & the Built Environment, Health & Wellness, and FID.\n\nType: Open Day\nCampus: Bellville Campus & District Six Campus\nVenue: Major Sports Hall (Bellville) & Multipurpose Hall (D6)\nTime: 09:00 - 16:00\nOrganizer: CPUT Marketing & Communication\nContact: info@cput.ac.za', 'EVENT', 'open-day, faculties, academics', 1, '2026-05-09 09:00:00'),
(6, 'Inter-Campus Shuttle Service Schedule Update (Bellville <-> D6)', 'Peak hour departure intervals have been adjusted to every 20 minutes between Bellville and District Six. Please tap your student card when boarding. Capacity is strictly seated.\n\nType: Campus Operations\nCampus: All Campuses\nVenue: Bus Terminals (Bellville North Gate / D6 Bus Shed)\nTime: Daily (06:30 - 21:00)\nOrganizer: CPUT Transport Department\nContact: transport@cput.ac.za', 'ANNOUNCEMENT', 'shuttle, transport, logistics', 1, '2026-10-01 06:30:00'),
(7, 'District Six & Bellville 24/7 Study Labs Extended Hours for Exams', 'Library study hubs will remain open 24/7 for semester 2 final exams. Security guards on duty and night shuttle drop-offs available for nearby accredited residences.\n\nType: Academic Services\nCampus: District Six & Bellville\nVenue: Library Complex Study Rooms\nTime: 24 Hours (Access Control via Biometrics)\nOrganizer: CPUT Libraries\nContact: library@cput.ac.za', 'ANNOUNCEMENT', 'library, study, exams, 24-7', 1, '2026-10-15 00:00:00');

-- Insert Products (Marketplace Listings)
INSERT IGNORE INTO `products` (`id`, `title`, `description`, `price`, `category`, `condition_name`, `is_eco_friendly`, `is_available`, `location`, `seller_id`) VALUES 
(1, 'Engineering Maths 1 & Mechanics Textbook + Casio fx-991ZA Plus', 'Hardly used Advanced Engineering Mathematics 8th Ed + Casio scientific calculator approved for CPUT exam venues. No highlighted pages.\n\nContact: chat-dm / 071-xxx-xxxx', 450.00, 'Textbooks & Equipment', 'Used - Good', FALSE, TRUE, 'Bellville Campus - Meet at Student Centre or Engineering Cafe', 2),
(2, 'Hospitality / Chef Knife Set & Uniform (Granger Bay Campus)', 'Complete Wüsthof student starter knife roll with whetstone plus size M chef whites and safety clogs. Clean and compliant with Hotel School kitchen inspection standards.\n\nContact: chat-dm', 850.00, 'Academic Gear', 'Used - Good', FALSE, TRUE, 'Granger Bay Campus - Granger Bay Hotel School foyer', 3),
(3, 'Single Room Sublet in Accredited Res near D6 (Hanover Street)', 'Furnished single room with desk, high-speed Wi-Fi, biometric entry, backup solar power for loadshedding, and communal kitchen. Looking for clean male/female student.\n\nContact: chat-dm', 4200.00, 'Student Housing', 'N/A', FALSE, TRUE, 'District Six Campus - Buitenkant / Constitution St area (5 min walk to campus)', 4),
(4, 'LOST: Black Targus Laptop Bag with Student Card inside FID Lab 2.4', 'Left behind during Wednesday afternoon Maya tutorial. Contains external hard drive with major project files and CPUT student ID card. Please return to D6 security desk or DM me.\n\nContact: chat-dm', 0.00, 'Lost & Found', 'N/A', FALSE, TRUE, 'District Six Campus - Design Building 2nd Floor', 5);
